import { ChatOpenAI } from "@langchain/openai";
import { readFile, createDeepAgent } from "deepagents";
import { DEEP_AGENT_INSTRUCTIONS } from "@/lib/agent/deepagent.prompts";
import type { DeepAgentResult } from "@/lib/agent/deepagent.types";
import {
  buildPromptWithSessionQueryHistory,
  loadSessionContextFiles,
  logGeneratedPrompt,
  writeLastPromptMarkdown
} from "@/lib/agent/deepagent-tools";
import type { ServerConfig } from "@/lib/types";

function extractTextContent(content: unknown): string {
  if (typeof content === "string") {
    return content;
  }

  if (Array.isArray(content)) {
    return content
      .map((chunk) => {
        if (typeof chunk === "string") return chunk;
        if (chunk && typeof chunk === "object" && "text" in (chunk as Record<string, unknown>)) {
          return String((chunk as Record<string, unknown>).text ?? "");
        }
        return "";
      })
      .join("\n");
  }

  if (content && typeof content === "object") {
    return JSON.stringify(content);
  }

  return "";
}

function parseAgentJson(text: string): DeepAgentResult {
  const trimmed = text.trim();

  try {
    const parsed = JSON.parse(trimmed) as { query?: string; reasoning?: string };
    if (parsed.query) {
      return {
        query: parsed.query,
        reasoning: parsed.reasoning || "Generated by deepagents"
      };
    }
  } catch {
    // Continue to regex extraction.
  }

  const match = trimmed.match(/\{[\s\S]*\}/);
  if (match) {
    const parsed = JSON.parse(match[0]) as { query?: string; reasoning?: string };
    if (parsed.query) {
      return {
        query: parsed.query,
        reasoning: parsed.reasoning || "Generated by deepagents"
      };
    }
  }

  throw new Error("Deep agent did not return valid JSON with a query");
}

export async function generateGremlinWithDeepAgent(
  prompt: string,
  server: ServerConfig,
  sessionId: string
): Promise<DeepAgentResult> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error("OPENAI_API_KEY is required");
  }

  const model = process.env.OPENAI_MODEL || "gpt-4.1-mini";

  const llm = new ChatOpenAI({
    apiKey,
    model,
    temperature: 0.1
  });

  const agent = createDeepAgent({
    model: llm,
    tools: [readFile],
    instructions: DEEP_AGENT_INSTRUCTIONS
  });

  const [dataModelAndContext, promptWithHistory] = await Promise.all([
    loadSessionContextFiles(sessionId),
    buildPromptWithSessionQueryHistory(sessionId, prompt)
  ]);
  const { dataModel, janusRuntimeContext } = dataModelAndContext;

  const sessionRuntimeContext = {
    sessionId,
    serverId: server.id,
    contextUpdatedAt: new Date().toISOString(),
    schemaAndIndexes: janusRuntimeContext
  };

  await logGeneratedPrompt({
    sessionId,
    serverId: server.id,
    model,
    instructions: DEEP_AGENT_INSTRUCTIONS,
    prompt,
    promptWithHistory,
    files: {
      graph_datamodel_json: dataModel,
      janusgraph_runtime_context_json: sessionRuntimeContext
    }
  });

  const result = await agent.invoke({
    messages: [{ role: "user", content: promptWithHistory }],
    files: {
      "graph_datamodel.json": JSON.stringify(dataModel, null, 2),
      "/graph_datamodel.json": JSON.stringify(dataModel, null, 2),
      "janusgraph_runtime_context.json": JSON.stringify(sessionRuntimeContext, null, 2),
      "/janusgraph_runtime_context.json": JSON.stringify(sessionRuntimeContext, null, 2)
    }
  });

  const lastMessage = Array.isArray(result?.messages) ? result.messages.at(-1) : undefined;
  const content = extractTextContent((lastMessage as { content?: unknown } | undefined)?.content);

  if (!content) {
    await writeLastPromptMarkdown({
      sessionId,
      serverId: server.id,
      model,
      prompt: promptWithHistory,
      agentRawResponse: ""
    });
    throw new Error("Deep agent returned empty content");
  }

  try {
    const parsed = parseAgentJson(content);
    await writeLastPromptMarkdown({
      sessionId,
      serverId: server.id,
      model,
      prompt: promptWithHistory,
      agentRawResponse: content,
      parsedResponse: parsed
    });
    return parsed;
  } catch (error) {
    await writeLastPromptMarkdown({
      sessionId,
      serverId: server.id,
      model,
      prompt: promptWithHistory,
      agentRawResponse: content,
      parseError: error instanceof Error ? error.message : "Unknown parse error"
    });
    throw error;
  }
}
